{
    "language": "es",
    "messages": [
        {
            "id": "Failed to add an institute access server with URL: '{Identifier}'",
            "message": "Failed to add an institute access server with URL: '{Identifier}'",
            "translation": "Error al agregar el servidor de acceso a la institución. URL del servidor: '{Identifier}'",
            "placeholders": [
                {
                    "id": "Identifier",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "identifier"
                }
            ]
        },
        {
            "id": "Failed to add a secure internet server with organisation ID: '{Identifier}'",
            "message": "Failed to add a secure internet server with organisation ID: '{Identifier}'",
            "translation": "No se pudo añadir un servidor de internet seguro con ID de organización: '{Identifier}'",
            "placeholders": [
                {
                    "id": "Identifier",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "identifier"
                }
            ]
        },
        {
            "id": "Failed to add a server with URL: '{Identifier}'",
            "message": "Failed to add a server with URL: '{Identifier}'",
            "translation": "No se pudo añadir un servidor con URL: '{Identifier}'",
            "placeholders": [
                {
                    "id": "Identifier",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "identifier"
                }
            ]
        },
        {
            "id": "The input: '{Identifier}' is not a valid URL",
            "message": "The input: '{Identifier}' is not a valid URL",
            "translation": "La entrada: '{Identifier}' no es una URL válida",
            "placeholders": [
                {
                    "id": "Identifier",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "identifier"
                }
            ]
        },
        {
            "id": "The client tried to autoconnect to the VPN server: '{Identifier}', but you need to authorizate again. Please manually connect again.",
            "message": "The client tried to autoconnect to the VPN server: '{Identifier}', but you need to authorizate again. Please manually connect again.",
            "translation": "El cliente intentó autoconectarse al servidor VPN: '{Identifier}', pero necesita autorizarse de nuevo. Por favor, conéctese manualmente de nuevo.",
            "placeholders": [
                {
                    "id": "Identifier",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "identifier"
                }
            ]
        },
        {
            "id": "The client tried to autoconnect to the VPN server: '{Identifier}', but the operation failed to complete",
            "message": "The client tried to autoconnect to the VPN server: '{Identifier}', but the operation failed to complete",
            "translation": "El cliente intentó autoconectarse al servidor VPN: {Identifier}', pero la operación no se ha completado",
            "placeholders": [
                {
                    "id": "Identifier",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "identifier"
                }
            ]
        },
        {
            "id": "Failed to connect to server: '{Identifier}'",
            "message": "Failed to connect to server: '{Identifier}'",
            "translation": "Error al conectar con el servidor: '{Identifier}'",
            "placeholders": [
                {
                    "id": "Identifier",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "identifier"
                }
            ]
        },
        {
            "id": "Failed to obtain a VPN configuration for server: '{Identifier}'",
            "message": "Failed to obtain a VPN configuration for server: '{Identifier}'",
            "translation": "Error al obtener una configuración VPN para el servidor: '{Identifier}'",
            "placeholders": [
                {
                    "id": "Identifier",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "identifier"
                }
            ]
        },
        {
            "id": "Failed to obtain the list of organizations",
            "message": "Failed to obtain the list of organizations",
            "translation": "No se ha podido obtener la lista de las organizaciones"
        },
        {
            "id": "Failed to obtain the list of servers",
            "message": "Failed to obtain the list of servers",
            "translation": "Error al obtener la lista de los servidores"
        },
        {
            "id": "Timeout reached contacting URL: '{URL}'",
            "message": "Timeout reached contacting URL: '{URL}'",
            "translation": "Se ha alcanzado el tiempo de espera para conectar con la URL: {URL}",
            "placeholders": [
                {
                    "id": "URL",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "tErr.URL"
                }
            ]
        },
        {
            "id": "{Msg}. The cause of the error is: {Error}.",
            "message": "{Msg}. The cause of the error is: {Error}.",
            "translation": "{Msg}. La causa del error es: {Error}.",
            "placeholders": [
                {
                    "id": "Msg",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "msg"
                },
                {
                    "id": "Error",
                    "string": "%[2]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 2,
                    "expr": "e.wrapped.Error()"
                }
            ]
        },
        {
            "id": "An internal error occurred",
            "message": "An internal error occurred",
            "translation": "Se ha producido un error"
        }
    ]
}