{
    "language": "nl",
    "messages": [
        {
            "id": "The log file with directory: '{Directory}' failed to initialize",
            "message": "The log file with directory: '{Directory}' failed to initialize",
            "translation": "Het log bestand met pad: '{Directory}' kan niet aangemaakt worden",
            "placeholders": [
                {
                    "id": "Directory",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "directory"
                }
            ]
        },
        {
            "id": "An error occurred after getting the discovery files for the list of organizations",
            "message": "An error occurred after getting the discovery files for the list of organizations",
            "translation": "Er is een fout opgetreden met het ophalen van de lijst van organisaties"
        },
        {
            "id": "An error occurred after getting the discovery files for the list of servers",
            "message": "An error occurred after getting the discovery files for the list of servers",
            "translation": "Er is een fout opgetreden met het ophalen van de lijst van servers"
        },
        {
            "id": "The current server could not be found when getting it for expiry",
            "message": "The current server could not be found when getting it for expiry",
            "translation": "De huidige VPN server kon niet worden gevonden"
        },
        {
            "id": "The client tried to autoconnect to the VPN server: {Namesrv}, but no secure internet location is found. Please manually connect again",
            "message": "The client tried to autoconnect to the VPN server: {Namesrv}, but no secure internet location is found. Please manually connect again",
            "translation": "De client wilde automatisch verbinden met VPN server: {Namesrv}, maar de huidige locatie is niet gevonden. U moet opnieuw handmatig verbinden",
            "placeholders": [
                {
                    "id": "Namesrv",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "server.Name(srv)"
                }
            ]
        },
        {
            "id": "The secure internet location could not be set",
            "message": "The secure internet location could not be set",
            "translation": "De locatie voor de secure internet server kon niet opgeslagen"
        },
        {
            "id": "The client tried to autoconnect to the VPN server: {Namesrv}, but you need to authorizate again. Please manually connect again",
            "message": "The client tried to autoconnect to the VPN server: {Namesrv}, but you need to authorizate again. Please manually connect again",
            "translation": "De client wilde automatisch verbinden met VPN server: {Namesrv}, maar authorizatie is nodig. U moet handmatig opnieuw verbinden",
            "placeholders": [
                {
                    "id": "Namesrv",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "server.Name(srv)"
                }
            ]
        },
        {
            "id": "The authorization procedure failed to complete",
            "message": "The authorization procedure failed to complete",
            "translation": "Het authorizatie proces kon niet voltooid worden"
        },
        {
            "id": "The client tried to autoconnect to the VPN server: {Namesrv}, but no valid profiles were found. Please manually connect again",
            "message": "The client tried to autoconnect to the VPN server: {Namesrv}, but no valid profiles were found. Please manually connect again",
            "translation": "De client wilde automatisch verbinden met VPN server: {Namesrv}, maar er was geen geldig profiel gevinden. U moet handmatig opnieuw verbinden",
            "placeholders": [
                {
                    "id": "Namesrv",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "server.Name(srv)"
                }
            ]
        },
        {
            "id": "No suitable profiles could be found",
            "message": "No suitable profiles could be found",
            "translation": "Er zijn geen profielen gevonden om mee te verbinden"
        },
        {
            "id": "Profile with ID: '{PID}' could not be set",
            "message": "Profile with ID: '{PID}' could not be set",
            "translation": "Het profiel met identiteit: '{PID}' kon niet opgeslagen worden",
            "placeholders": [
                {
                    "id": "PID",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "pID"
                }
            ]
        },
        {
            "id": "Profile with ID: '{PID}' could not be obtained from the server",
            "message": "Profile with ID: '{PID}' could not be obtained from the server",
            "translation": "Het profiel met identiteit: '{PID}' kon niet opgehaald worden van de server",
            "placeholders": [
                {
                    "id": "PID",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "pID"
                }
            ]
        },
        {
            "id": "The identifier that was passed to the library is incorrect",
            "message": "The identifier that was passed to the library is incorrect",
            "translation": "De identiteit die aan de library werd gegeven is niet correct"
        },
        {
            "id": "Could not retrieve institute access server with URL: '{Identifier}' from discovery",
            "message": "Could not retrieve institute access server with URL: '{Identifier}' from discovery",
            "translation": "De institute access server met URL: '{Identifier}' kan niet opgehaald worden van discovery",
            "placeholders": [
                {
                    "id": "Identifier",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "identifier"
                }
            ]
        },
        {
            "id": "The institute access server with URL: '{Identifier}' could not be added",
            "message": "The institute access server with URL: '{Identifier}' could not be added",
            "translation": "De institute access server met URL: '{Identifier}' kan niet toegevoegd worden",
            "placeholders": [
                {
                    "id": "Identifier",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "identifier"
                }
            ]
        },
        {
            "id": "The secure internet server with organisation ID: '{Identifier}' could not be retrieved from discovery",
            "message": "The secure internet server with organisation ID: '{Identifier}' could not be retrieved from discovery",
            "translation": "De secure internet server met identiteit: '{Identifier}' kan niet opgehaald worden van discovery",
            "placeholders": [
                {
                    "id": "Identifier",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "identifier"
                }
            ]
        },
        {
            "id": "The secure internet server with organisation ID: '{Identifier}' could not be added",
            "message": "The secure internet server with organisation ID: '{Identifier}' could not be added",
            "translation": "De secure internet server met identiteit: '{Identifier}' kan niet toegevoegd worden",
            "placeholders": [
                {
                    "id": "Identifier",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "identifier"
                }
            ]
        },
        {
            "id": "The custom server with URL: '{Identifier}' could not be added",
            "message": "The custom server with URL: '{Identifier}' could not be added",
            "translation": "De server met URL: '{Identifier}' kan niet toegevoegd worden",
            "placeholders": [
                {
                    "id": "Identifier",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "identifier"
                }
            ]
        },
        {
            "id": "The VPN configuration could not be obtained",
            "message": "The VPN configuration could not be obtained",
            "translation": "De VPN configuratie kan niet opgehaald worden"
        },
        {
            "id": "The current profile could not be found",
            "message": "The current profile could not be found",
            "translation": "Het huidig profiel kan niet gevonden worden"
        },
        {
            "id": "Identifier: '{Identifier}' for server with type: '{Type}' is not valid",
            "message": "Identifier: '{Identifier}' for server with type: '{Type}' is not valid",
            "translation": "De identiteit: '{Identifier}' voor server met type: '{Type}' is niet geldig",
            "placeholders": [
                {
                    "id": "Identifier",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "identifier"
                },
                {
                    "id": "Type",
                    "string": "%[2]d",
                    "type": "github.com/eduvpn/eduvpn-common/types/server.Type",
                    "underlyingType": "int8",
                    "argNum": 2,
                    "expr": "_type"
                }
            ]
        },
        {
            "id": "The operation for getting a VPN configuration was canceled",
            "message": "The operation for getting a VPN configuration was canceled",
            "translation": "De procedure om een VPN configuratie op te halen is verbroken"
        },
        {
            "id": "Failed to set the server with identifier: '{Identifier}' as the current",
            "message": "Failed to set the server with identifier: '{Identifier}' as the current",
            "translation": "De server met identiteit: '{Identifier}' kan niet als de hudige server gezet worden",
            "placeholders": [
                {
                    "id": "Identifier",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "identifier"
                }
            ]
        },
        {
            "id": "Identifier: '{Identifier}' for server with type: '{Type}' is not valid for removal",
            "message": "Identifier: '{Identifier}' for server with type: '{Type}' is not valid for removal",
            "translation": "Identiteit: '{Identifier}' voor server met type: '{Type}' is niet geldig om verwijderd te worden",
            "placeholders": [
                {
                    "id": "Identifier",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "identifier"
                },
                {
                    "id": "Type",
                    "string": "%[2]d",
                    "type": "github.com/eduvpn/eduvpn-common/types/server.Type",
                    "underlyingType": "int8",
                    "argNum": 2,
                    "expr": "_type"
                }
            ]
        },
        {
            "id": "Failed to get the current server to cleanup the connection",
            "message": "Failed to get the current server to cleanup the connection",
            "translation": "De huidige server kan niet opgehaald worden om de connectie te verwijderen"
        },
        {
            "id": "Failed to cleanup the VPN connection for the current server",
            "message": "Failed to cleanup the VPN connection for the current server",
            "translation": "De VPN connectie is niet volledig opgeruimd"
        },
        {
            "id": "No secure internet server available to set a location for",
            "message": "No secure internet server available to set a location for",
            "translation": "Er is geen \"secure internet\" server beschikbaar om de locatie voor in te stellen"
        },
        {
            "id": "Failed to get current server for renewing the session",
            "message": "Failed to get current server for renewing the session",
            "translation": "De huidige server kan niet opgehaald worden om de sessie te hernieuwen"
        },
        {
            "id": "Failover failed to complete with gateway: '{Gateway}' and MTU: '{Mtu}'",
            "message": "Failover failed to complete with gateway: '{Gateway}' and MTU: '{Mtu}'",
            "translation": "Het 'failover' proces kan niet voltooid worden. Gateway: '{Gateway}' en MTU: '{Mtu}'",
            "placeholders": [
                {
                    "id": "Gateway",
                    "string": "%[1]s",
                    "type": "string",
                    "underlyingType": "string",
                    "argNum": 1,
                    "expr": "gateway"
                },
                {
                    "id": "Mtu",
                    "string": "%[2]d",
                    "type": "int",
                    "underlyingType": "int",
                    "argNum": 2,
                    "expr": "mtu"
                }
            ]
        },
        {
            "id": "timeout reached",
            "message": "timeout reached",
            "translation": "Er is een time-out opgetreden in de verbinding. Controleer uw internetverbinding"
        },
        {
            "id": "with cause:",
            "message": "with cause:",
            "translation": "met oorzaak:"
        },
        {
            "id": "An internal error occurred",
            "message": "An internal error occurred",
            "translation": "Een interne fout is opgetreden"
        }
    ]
}
